name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/PeakyFlow.Aspire/PeakyFlow.Aspire.Mobile/PeakyFlow.Aspire.Mobile.csproj
      
    - name: Build
      run: dotnet build src/PeakyFlow.Aspire/PeakyFlow.Aspire.Mobile/PeakyFlow.Aspire.Mobile.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish src/PeakyFlow.Aspire/PeakyFlow.Aspire.Mobile/PeakyFlow.Aspire.Mobile.csproj --configuration Release --output ./publish
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './publish/wwwroot'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
